# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d78be3042d6cc80a6af62ace2d2bcbb552fbd1a31547a922b7530d9c8972670ee54896c6bba7748854e868b965471b195ae3b009250bf7efcb8df42c9b08c41

test:
  secret_key_base: 082306ca71ac727d84eb9bb046ddc8dea16a5bc80b24ca65e8afd1dd76cef8fb72eff07b416f6955ef5bd2c660ad0cac3d874c2dc0ec76d8491a6aa4dbed413e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
